---
apiVersion: v1
kind: Service
metadata:
  namespace: nginx-test
  name: nginx-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app: nginx

---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  namespace: nginx-test
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.0
        ports:
        - containerPort: 80
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      restartPolicy: Never
      ttlSecondsAfterFinished: 600
      containers:
        - name: smoke-test
          image: appropriate/curl:latest
          args: 
          - http://nginx-service.nginx-test.svc:8080
