---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      ttlSecondsAfterFinished: 600
      containers:
        - name: smoke-test
          image: appropriate/curl:latest
          args: 
          - http://nginx-service.nginx-test.svc:8080
